name: picasso
description: A modular cross platform image editor package for flutter.
version: 0.0.3+2
repository: https://github.com/helightdev/picasso

environment:
  sdk: '>=3.0.0-290.1.beta  <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  meta: ^1.9.0
  collection: ^1.17.1
  intl: ^0.18.0
  image: ^4.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: {}